### ISSUE TITLE
Not working with iTerm2 3.x

### ISSUE THREAD

**Issue by ushuz** [wbond/sublime_terminal#125] opened 2016-07-25 07:40 UTC
Latest iTerm2 (3.0.5) updated its applescript syntax, therefore `iTerm.sh` stops working.

New syntax documentation: https://iterm2.com/documentation-scripting.html

**Comment by twolfson** [comment] 2016-07-25 15:50
This is a duplicate of #89

**Closed by twolfson** 2016-07-25 15:50 UTC
