### ISSUE TITLE
User Keybindings do not override Defaults on Windows 7

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_terminal#32] opened 2012-12-18 20:42 UTC
I don't get this behavior from any other package I have installed. No matter what I assign in User keybindings the defaults are still active and not overridden properly. I have to comment out  the entries in Defaults to get expected behavior.

**Comment by twolfson** [comment] 2015-06-13 12:15
For the sake of discussion, I am going to consider this a duplicate of #17 where we want to relocate key bindings.

**Closed by twolfson** 2015-06-13 12:15 UTC
