### ISSUE TITLE
Open iTerm with Command

### ISSUE THREAD

**Issue by jamesstidard** [wbond/sublime_terminal#202] opened 2019-02-09 13:56 UTC
Hi,

I was wondering if it is possible to hand the `iTerm2-v3.sh` script additional commands to write to iTerm once it is open. I would like to be able to open iTerm with a preloaded command to instantly run.

From reading the iTerm2-v3.sh script, I don't think this is currently possible (though my apple script and bash skills are limited). Is that the case? Would it be something that could be easily added?

```
{
    "terminal": "iTerm2-v3.sh",
    "parameters": ["--open-in-tab", "--cmd", "ls"],
}
```

Thanks for the plugin.

**Comment by twolfson** [comment] 2019-02-10 00:42
Can you explain your use case further?

**Comment by jamesstidard** [comment] 2019-02-10 00:54
sure. I'm trying to offload some build systems to my terminal for longer running processes - like running servers. Sublime isn't really built to handle simultaneous builds, so spitting them out over to my terminal seems like the way to go.

**Comment by twolfson** [comment] 2019-02-10 00:57
Got it. This is a duplicate of #177 and #175. We'd prefer to point people to other projects which are targetted at building in terminals for scenarios like this. Here are alternatives:

- https://packagecontrol.io/packages/Shell%20Exec
- https://packagecontrol.io/packages/Console%20Exec
- https://packagecontrol.io/packages/Exec%20In%20Window

**Closed by twolfson** 2019-02-10 00:57 UTC

**Comment by jamesstidard** [comment] 2019-02-10 01:00
Ah OK, sorry missed these issues when I posted. I'll take a look at these other packages. Thanks
