### ISSUE TITLE
Open terminal as a build system

### ISSUE THREAD

**Issue by myalcin81** [wbond/sublime_terminal#215] opened 2020-07-30 16:59 UTC
Could you support to use of terminal as a build system as Terminus did?

Terminus build system usage of their docs;

```
Terminus Build System
It is possible to use Terminus as a build system. The target terminus_exec is a drop in replacement of the default target exec. It takes exact same arguments as terminus_open except that their default values are set differently.

terminus_cancel_build is used to cancel the build when user runs cancel_build triggered by ctrl+c (macOS) or ctrl+break (Windows / Linux).

The following is an example of build system define in project settings that run a python script

{
    "build_systems":
    [
        {
            "name": "Hello World",
            "target": "terminus_exec",
            "cancel": "terminus_cancel_build",
            "cmd": [
                "bash", "-c", "echo helloworld"
            ],
            "working_dir": "$folder"
        }
    ]
}
The same Hello World example could be specified via a .sublime-build file.

{
    "target": "terminus_exec",
    "cancel": "terminus_cancel_build",
    "cmd": [
        "bash", "-c", "echo helloworld"
    ],
    "working_dir": "$folder"
}
Instead of cmd, user could also specify shell_cmd. In macOS and linux, a bash shell will be invoked; and in Windows, cmd.exe will be invoked.

{
    "target": "terminus_exec",
    "cancel": "terminus_cancel_build",
    "shell_cmd": "echo helloworld",
    "working_dir": "$folder"
}

```

`https://packagecontrol.io/packages/Terminus`

**Comment by twolfson** [comment] 2020-07-30 18:03
This is a duplicate of #175, #177, and #202. Have you tried a package like https://packagecontrol.io/packages/Console%20Exec ?

**Closed as completed by twolfson** 2020-07-30 18:03 UTC
Labels: duplicate, question
