### ISSUE TITLE
iTerm.sh no longer working with iTerm2 Build 2.9.2x

### ISSUE THREAD

**Issue by sunglee** [wbond/sublime_terminal#109] opened 2016-02-19 18:41 UTC
With the new release of [iTerm2 v.3](https://iterm2.com/version3.html), `Open Terminal Here...` command is not working any more. Any solution?

**Comment by jajohnso** [comment] 2016-02-19 21:05
I just ran into this as well.

**Comment by twolfson** [comment] 2016-02-20 05:42
This is a duplicate of #89, please see the discussion there.

**Closed by twolfson** 2016-02-20 05:42 UTC
