### ISSUE TITLE
Starting Terminal causes some errors. (Windows 8)

### ISSUE THREAD

**Issue by fjctlzy** [wbond/sublime_terminal#37] opened 2013-03-05 14:23 UTC
When I use the Terminal(Ctrl+Shift+T) to start a Terminal, and then this happened...I will try to open a powershell, but...

D:\Users\Tony\AppData\Roaming\Sublime Text 2\Packages\Terminal\PS.ps1 : 无法将“D:\Users\Tony\AppData\Roaming\Sublime T
ext 2\Packages\Terminal\PS.ps1”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确
保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ D:\Users\Tony\AppData\Roaming\Sublime` Text` 2\Packages\Terminal\PS.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Users\Tony\A...Terminal\PS.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\work\cbupe_svn\aliflask>

**Comment by shivapoudel** [comment] 2015-06-13 11:17
@fjctlzy I am Windows 8 user and can't reproduce this bug?

**Comment by twolfson** [comment] 2015-06-13 12:18
I would guess this is an encoding error but it isn't clear. @fjctlzy Do you have any custom settings being used?

**Comment by twolfson** [comment] 2015-07-13 02:27
It has been 1 month since we replied on this issue but with no updates from the commenters. Closing this issue for now.

**Closed by twolfson** 2015-07-13 02:27 UTC
