### ISSUE TITLE
Version 3 Beta - iTerm2 is not suppoart

### ISSUE THREAD

**Issue by aCodify** [wbond/sublime_terminal#111] opened 2016-03-08 11:46 UTC
code config is not use

{
"terminal": "iTerm.sh",
}

**Comment by twolfson** [comment] 2016-03-08 20:41
This is a duplicate of #89 and #109. Please see #90 for a resolution.

**Closed by twolfson** 2016-03-08 20:41 UTC

**Comment by aCodify** [comment] 2016-03-12 10:16
thank you @twolfson
