### ISSUE TITLE
passing a custom command on the terminal

### ISSUE THREAD

**Issue by eliax1996** [wbond/sublime_terminal#177] opened 2017-10-12 13:30 UTC
it is possible to pass a custom string like the first command that will be executed by the terminal?

for example: 
press [ctrl]+[shift]+[t] in sublime

 and in the command line at the first line appear --> 

|------------------------------terminal------------------------------|
| user/my/code/location/file $   my_command_string                            
|                                                                                                                 
|                                                                                                                 
|                                                                                                                 
|                                                                                                                 
|                                                                                                                 
---------------------------------------------------------------------|

**Comment by twolfson** [comment] 2017-10-13 03:58
This is a duplicate of #175. We don't support running commands in terminals. Here are plugins which do:

- Sublime Text's build system
- https://packagecontrol.io/packages/Shell%20Exec
- https://packagecontrol.io/packages/Console%20Exec
- https://packagecontrol.io/packages/Exec%20In%20Window

**Closed by twolfson** 2017-10-13 03:58 UTC
