### ISSUE TITLE
Default open_terminal key binding overrides "Reopen Closed File"

### ISSUE THREAD

**Issue by XenHat** [wbond/sublime_terminal#57] opened 2014-01-18 22:31 UTC
I noticed that the keybind shortcut for open_terminal overrides "reopen closed file".

While the terminal plugin is active, the ctrl+shift+T shortcut seems to disappear from the menu, indicating that it is no longer bound to this function.
However, I use the re-open feature a lot, and I am somewhat against overriding a shortcut for a feature that could be considered "core feature".

I could not think of a better shortcut, though.

**Comment by mehdilamaaffar** [comment] 2015-01-14 18:01
i got the some problem

**Comment by twolfson** [comment] 2015-06-13 12:25
This is a duplicate of #17. Please follow the discussion there.

**Closed by twolfson** 2015-06-13 12:25 UTC
