### ISSUE TITLE
open_terminal cammand not support iTerm 3.0.5 in mac 

### ISSUE THREAD

**Issue by zivsu** [wbond/sublime_terminal#127] opened 2016-08-04 14:23 UTC
prompt that /Users/ziv/Library/Application Support/Sublime Text 3/Packages/Terminal/iTerm.sh was not found， Did you encounter this problem？

**Comment by twolfson** [comment] 2016-08-04 14:54
I don't follow. Can you elaborate on how you received that message?

**Comment by zivsu** [comment] 2016-08-04 17:48
Sorry, my bed. My iTerm version is 3.0.5, and I execute open_terminal command, the iTerm not respond. 
I read you source code quickly. I found the iTerm.sh not support iTerm 2 3.0.5 version.
Because iTerm 2 3.0.5 application name is **iTerm2** when running, but the name in your osascript is **iTerm**. 
Can you fix the package compatible with iTerm2 3.0.5 version?
My english is so poor, sorry.

**Comment by zivsu** [comment] 2016-08-04 17:51
![image](https://cloud.githubusercontent.com/assets/8110132/17412386/155391e6-5aaf-11e6-9687-ee834abfa200.png)

**Comment by zivsu** [comment] 2016-08-04 17:54
![image](https://cloud.githubusercontent.com/assets/8110132/17412477/7881bd6a-5aaf-11e6-8d33-ab8caffe4680.png)

**Comment by zivsu** [comment] 2016-08-04 17:55
![image](https://cloud.githubusercontent.com/assets/8110132/17412505/a36bb21a-5aaf-11e6-93e4-eb4a21e5a7a7.png)

**Comment by Parziv4l** [comment] 2016-08-04 18:19
I am also having this same issue

**Comment by twolfson** [comment] 2016-08-05 09:38
This is a duplicate of #89, please see #89 for discussion/resolution

**Closed by twolfson** 2016-08-05 09:38 UTC

**Comment by zivsu** [comment] 2016-08-05 15:26
Yes, I solve it, Thanks. You are so powerful.
