### ISSUE TITLE
Disable open_terminal shortcut

### ISSUE THREAD

**Issue by dcrck** [wbond/sublime_terminal#63] opened 2014-06-11 11:26 UTC
How can I disable super+shift+t as the open_terminal shortcut? Because I need it for opening my most recently closed files.

**Comment by twolfson** [comment] 2015-06-13 12:39
This is a duplicate of #17. We are finally getting back to fixing this issue for good. Sorry for the delay.

**Closed by twolfson** 2015-06-13 12:39 UTC
